### ISSUE TITLE
Calendar を使用するとページのレンダリングでエラーが出る

### ISSUE THREAD

**Issue by nikogoli** [nikogoli/testing-shadcn-ui-in-fresh#5]
Calender は react-day-picker に依存しているが、この react-day-picker  関連で以下のエラーが出るので fresh が動かない。

```
An error occurred during route handling or page rendering. TypeError: Cannot read properties of undefined (reading 'current')
    at Object.i (https://esm.sh/v133/react-day-picker@8.9.1/X-YS9AdHlwZXMvcmVhY3Q6cHJlYWN0L2NvbXBhdCxyZWFjdDpwcmVhY3QvY29tcGF0CmUvKg/denonext/react-day-picker.mjs:2:2058)
    at Object.Hn (https://esm.sh/v133/react-day-picker@8.9.1/X-YS9AdHlwZXMvcmVhY3Q6cHJlYWN0L2NvbXBhdCxyZWFjdDpwcmVhY3QvY29tcGF0CmUvKg/denonext/react-day-picker.mjs:2:31509)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3034)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3599)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3599)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2545)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:4847)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3599)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2545)
    at v (https://esm.sh/v132/preact-render-to-string@6.2.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3599)
```

エラーが出ているのは以下の `_owner:a.current` の部分で、その上にある `e.__SECRET...._FIRED.ReactCurrentOwner` が `undefined` であるためにエラーになっていると思われる。
```js
function fr(){
  if(Re)return $;
  Re=1;
  var e=Xe,n=Symbol.for("react.element"),r=Symbol.for("react.fragment"),t=Object.prototype.hasOwnProperty,
     a=e.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,
     o={key:!0,ref:!0,__self:!0,__source:!0};
  
  function i(l,u,f){
    var c,p={},m=null,h=null;
    f!==void 0&&(m=""+f),u.key!==void 0&&(m=""+u.key),u.ref!==void 0&&(h=u.ref);
    for(c in u)t.call(u,c)&&!o.hasOwnProperty(c)&&(p[c]=u[c]);
    if(l&&l.defaultProps)for(c in u=l.defaultProps,u)p[c]===void 0&&(p[c]=u[c]);
    return{$$typeof:n,type:l,key:m,ref:h,props:p,_owner:a.current}
  }
  return $.Fragment=r,$.jsx=i,$.jsxs=i,$
}
```

**Comment by nikogoli** [comment]
React ⇔ preact/compat 間の互換性の問題のように思われるので、対処しない。

**Comment by nikogoli** [comment]
React ⇔ preact/compat 間の互換性の問題のように思われるので、対処しない。
